# Launch-level defaults for automode_tb4.launch.py - Foraging Mission
robot_namespace: ""
module_package: "basic_modules"

# Which controller to start: 'fsm' or 'bt'
controller_type: "bt"

# BT config (optional) - used when controller_type is 'bt'
# Foraging BT: exploration -> black floor -> phototaxis -> white floor -> anti-phototaxis -> grey floor -> exploration
# bt_config: "--bt-config --nroot 1 --nchildroot 6 --n0 2 --nchild0 2 --n00 6 --c00 2 --color00 1 --p00 1 --n01 5 --a01 2 --n1 2 --nchild1 2 --n10 6 --c10 2 --color10 3 --p10 1 --n11 5 --a11 3 --n2 2 --nchild2 2 --n20 6 --c20 2 --color20 2 --p20 1 --n21 5 --a21 0 --n3 5 --a3 0 --n4 5 --a4 0 --n5 5 --a5 0"

# FSM config - Foraging: exploration -> black floor -> phototaxis -> white floor -> anti-phototaxis -> grey floor -> exploration
fsm_config: "--fsm-config --nstates 3 --s0 0 --rwm0 50 --n0 1 --n0x0 0 --c0x0 2 --p0x0 1 --s1 2 --n1 1 --n1x0 1 --c1x0 1 --p1x0 1 --s2 3 --n2 1 --n2x0 0 --c2x0 0 --color2x0 2 --p2x0 1 "

ref_model: "ref_model_turtlebot4_gz_nav"

bt_config: "--bt-config --nroot 0 --nchildroot 3 --n0 2 --nchild0 2 --n00 6 --c00 2 --p00 1 --n01 5 --a01 2 --n1 2 --nchild1 2 --n10 6 --c10 1 --p10 1 --n11 5 --a11 3 --n2 2 --nchild2 2 --n20 6 --c20 0 --color20 2 --p20 1 --n21 5 --a21 0 --rwm21 50 "


# Results BT:
# [timer_shutdown-25] [INFO] [1769872206.619814076] [timer_shutdown]: Simulation time reached 10 minutes. Real time elapsed: 923.18s, RTF: 0.65
# [INFO] [1769872329.365909133] [foraging_scorer]: Scores: {'tb1': 5, 'tb2': 7, 'tb3': 5, 'tb4': 6} = 23
# pos data: foraging_bt_01.csv

# Results FSM:
# [timer_shutdown-25] [INFO] [1769873387.925671645] [timer_shutdown]: Simulation time reached 10 minutes. Real time elapsed: 792.11s, RTF: 0.76
# [INFO] [1769873387.629672139] [foraging_scorer]: Scores: {'tb1': 10, 'tb2': 8, 'tb3': 9, 'tb4': 7} = 34
# pos data: foraging_fsm_01.csv


