# Launch-level defaults for automode_tb4.launch.py - Flocking Mission
robot_namespace: ""
module_package: "basic_modules"

controller_type: "fsm"

# FSM config - Flocking: repulsion if too close, else attraction, else explore
# fsm_config: "--fsm-config --nstates 4 --s0 0 --rwm0 50 --n0 1 --n0x0 0 --c0x0 3 --p0x0 0.01 --w0x0 2 --s1 4 --att1 4 --n1 1 --n1x0 1 --c1x0 3 --p1x0 0.05 --w1x0 3 --s2 5 --rep2 2 --n2 2 --n2x0 1 --c2x0 4 --p2x0 0.1 --w2x0 3 --n2x1 2 --c2x1 4 --p2x1 0.01 --w2x1 3 --s3 0 --rwm3 50 --n3 1 --n3x0 0 --c3x0 1 --p3x0 1 "
fsm_config: "--fsm-config --nstates 4 --s0 0 --rwm0 50 --n0 1 --n0x0 0 --c0x0 3 --p0x0 1 --w0x0 1 --s1 4 --att1 1 --n1 1 --n1x0 1 --c1x0 3 --p1x0 0.0001 --w1x0 2 --s2 2 --n2 1 --n2x0 2 --c2x0 1 --p2x0 1 --s3 0 --rwm3 50 --n3 1 --n3x0 0 --c3x0 2 --p3x0 1 "


# BT config - Flocking: repulsion > attraction > explore
bt_config: "--bt-config --nroot 0 --nchildroot 3 --n0 6 --c00 4 --p00 1.0 --w00 2 --n01 5 --a01 4 --att01 4.0 --n02 5 --a02 0 --rwm02 50"

ref_model: "ref_model_turtlebot4_gz_nav"

# No working behavior neither fsm nor bt to this point