# Launch-level defaults for automode_tb4.launch.py - Dispersion Mission
robot_namespace: ""
module_package: "basic_modules"

controller_type: "bt"

# FSM config - Dispersion: repulsion if close, else explore
fsm_config: "--fsm-config --nstates 2 --s0 0 --rwm0 100 --n0 1 --n0x0 0 --c0x0 3 --p0x0 0.01 --w0x0 1 --s1 5 --rep1 1 --n1 1 --n1x0 0 --c1x0 4 --p1x0 0.1 --w1x0 1 "

# BT config - Dispersion: repulsion > explore
bt_config: "--bt-config --nroot 0 --nchildroot 2 --n0 2 --nchild0 2 --n00 6 --c00 3 --p00 1.0 --w00 1 --n01 5 --a01 5 --rep01 1 --n1 2 --nchild1 2 --n10 6 --c10 4 --p10 1.0 --w10 1 --n11 5 --a11 0 --rwm11 100 "

ref_model: "ref_model_turtlebot4_gz_nav" 

# Working (not perfect but shows dispersion behavior) need to be tested